name: Python CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Vérifie ton code depuis le repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Installe Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Tu peux changer la version de Python si nécessaire

    # Installe les dépendances nécessaires
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Exécute les tests
    - name: Run tests
      run: |
        python -m pytest test_operations.py
